// <auto-generated />
using AboutMe.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AboutMe.Data.Migrations
{
    [DbContext(typeof(AboutMeContext))]
    [Migration("20230705193456_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AboutMe.Business.Features.Forecasts.ForecastModel", b =>
                {
                    b.Property<int>("ForecastId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ForecastId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double>("TemperatureC")
                        .HasColumnType("float");

                    b.HasKey("ForecastId");

                    b.ToTable("Forecast", null, t =>
                        {
                            t.HasCheckConstraint("CK_Forecast_Description_AtLeastThreeChars", "LEN([Description]) >= 3");

                            t.HasCheckConstraint("CK_Forecast_Description_Trimmed", "LTRIM(RTRIM([Description])) = [Description]");

                            t.HasCheckConstraint("CK_Forecast_TemperatureC_GreaterThanAbsoluteZero", "ISNULL([TemperatureC], 1) >= -273.15");
                        });

                    b.HasData(
                        new
                        {
                            ForecastId = 1,
                            Description = "Balmy",
                            TemperatureC = 28.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
